// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using my_own_json_api.Models.Context;

namespace my_own_json_api.Migrations
{
    [DbContext(typeof(JSONContext))]
    [Migration("20190717125408_AddNewsTable")]
    partial class AddNewsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("my_own_json_api.Models.BitOfNews", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<string>("Date");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new { Id = "53e705b2-5b35-4ca1-a8ef-74897bcb309e", Body = "ipsum dolor sit amet, consectetur adipiscing elit. Sed ornare at nisi nec fermentum. Mauris commodo enim lorem, at congue leo volutpat quis. Fusce mollis justo dolor, sed malesuada ligula vehicula sit amet. Cras metus tortor, pharetra mollis nulla a, viverra vestibulum turpis. Quisque ultricies efficitur risus, sit amet laoreet nulla. Fusce auctor sapien in enim consectetur, vel feugiat ipsum varius. Sed non vestibulum risus.", Date = "17-07-2019, 03:54:08", ImageUrl = "http://hdwpro.com/wp-content/uploads/2019/01/Beautiful-Awesome-Wallpaper.jpg", Title = "commodo enim lorem, at congue leo volutpat quis" },
                        new { Id = "6cda4851-7eea-4870-a1f6-52484373900d", Body = "Donec mattis, est eget interdum eleifend, ligula lectus molestie velit, vitae bibendum ipsum augue et risus. Aliquam at erat a massa molestie accumsan id id sapien. Maecenas sagittis leo ac consequat gravida. Donec mattis nunc eget fringilla luctus. Fusce et sem tincidunt, tempor sem nec, pretium eros. Aenean quis finibus enim. Phasellus varius sem nulla, non dictum nisi maximus sed. Praesent porta velit vitae neque imperdiet, at malesuada risus accumsan.", Date = "17-07-2019, 03:54:08", ImageUrl = "http://www.photobackgroundhd.com/wp-content/uploads/2018/08/Full-HD-Nature-Images.jpg", Title = "vitae bibendum ipsum augue et risus" },
                        new { Id = "586a8572-9099-45dd-88e2-a15f269050fb", Body = "Sed et ligula non nisi cursus faucibus ut vitae sapien. Aenean id dictum arcu, at convallis lectus. Vestibulum faucibus luctus lectus, ut ultrices dolor sollicitudin nec. Vivamus quam diam, gravida non dui eu, rutrum semper odio. Praesent facilisis lobortis mi. Donec condimentum magna vitae mi pretium congue. Quisque ut fermentum orci, at volutpat nisl. Sed eget erat ac nisi sollicitudin ultrices. Praesent vel odio quam.", Date = "17-07-2019, 03:54:08", ImageUrl = "http://hdwpro.com/wp-content/uploads/2016/03/Cloudy-Weather-Full-HD-Wallpaper.jpg", Title = "aenean id dictum arcu, at convallis lectus" }
                    );
                });

            modelBuilder.Entity("my_own_json_api.Models.Todo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<string>("Date");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new { Id = "b16aff5c-ffde-4dd3-bf11-cd4dda43f948", Completed = false, Date = "17-07-2019, 03:54:08", Title = "lorem ipsum dolor sit amet" },
                        new { Id = "7fc9945b-7e0a-4865-b5c7-6ab7e9ac18f7", Completed = true, Date = "17-07-2019, 03:54:08", Title = "dolor sit amet consectetur adipisicing" },
                        new { Id = "754dfaef-bbb4-4200-9eb9-92fd40ef652c", Completed = false, Date = "17-07-2019, 03:54:08", Title = "iusto modi reiciendis voluptates corrupti minima saepe dolorum" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
