// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using my_own_json_api.Models.Context;

namespace my_own_json_api.Migrations
{
    [DbContext(typeof(JSONContext))]
    partial class JSONContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("my_own_json_api.Models.Todo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<string>("Date");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new { Id = "74c7c43c-724f-4b45-b8ea-113698cebb04", Completed = false, Title = "lorem ipsum dolor sit amet" },
                        new { Id = "da99f04d-ec39-4ac1-94e9-1139fb2ec286", Completed = true, Title = "dolor sit amet consectetur adipisicing" },
                        new { Id = "5488b6f2-7d1b-4f83-8550-8a331e2134f2", Completed = false, Title = "iusto modi reiciendis voluptates corrupti minima saepe dolorum" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
